const translations = {
    en: {
      "inicio.title": "HOME",
      "experiencias.title": "EXPERIENCES",
      "about.title": "ABOUT US",
      "contacto.title": "CONTACT",
      "legal.title": "LEGAL",
      "home.title": "Live a unique experience in Mendoza",
      "home.subtitle": "CHOOSE YOUR EXPERIENCE",
      "card.excursiones.title": "Group Tours",
      "card.excursiones.description": "Visit Mendoza, at the foot of the Andes, famous for its scenic beauty, wines, and cuisine. Stroll through its beautiful city and surrounding areas of imposing mountains, agricultural and wine-producing areas. Enjoy its spectacular landscapes while participating in outdoor activities.",
      "card.excursiones.button": "Discover",
      "card.winetours.title": "Wine Tours",
      "card.winetours.description": "Enjoy unique wine tourism experiences, from boutique wineries to historic vineyards, with guided tastings, exclusive pairings, and vineyard walks. Discover the art of wine with experts who will help you enjoy unforgettable moments in privileged settings.",
      "card.winetours.button": "Discover",
      "about.title2":"About us",
      "about.text":"We are a small tourism company in Mendoza, specializing in the wine tourism sector. Dedicated to inbound tourism for over 25 years, we have come a long way to understand and meet the needs of those who choose us, designing a unique and tailored experience according to their interests. We invite you to join us on a wonderful trip through Mendoza, with its mountains, its gastronomy, its wineries, and its people. Welcome!",
      "contact.title": "Contact us by email",
      "contact.subtitle": "We help you organize your best moments.",
      "form.name.label": "Name",
      "form.email.label": "Email",
      "form.phone.label": "Phone",
      "form.message.label": "Message",
      "form.send": "Send",
      "contact.whatsapp.title": "Or send us a WhatsApp",
      "legal.title2": "Legal Documents",
      "legal.subtitle": "Here you can find our legal documents and ways to file a claim. Click each link to download the corresponding file.",
      "legal.link1": "VIRTUAL ADDRESS CERTIFICATE",
      "legal.link2": "ENABLING LICENSE",
      "legal.link3": "CONSUMER DEFENSE",
      "legal.link4": "COMPLAINT AGAINST AN AGENCY",
      "filters.title": "Filter by:",
      "filters.all": "Show All",
      "filters.excursiones": "Group Tours",
      "filters.winetours": "Wine Tours",
      "title.excursiones": "Group Tours",
      "title.tourwinetours": "Wine Tours",
      "vermas": "See more",
      "vermenos": "See less",
      "excursion.altamontania.title": "High Mountains and Puente del Inca",
      "excursion.altamontania.subtitle": "Full-day excursion through the Andes Mountains.",
      "excursion.altamontania.vermas": "See more",
      "excursion.altamontania.description": "Full-day excursion to the Andes Mountains. You'll pass through the Potrerillos and Uspallata valleys, the Penitentes ski center, the Puente del Inca, and the Aconcagua viewpoint, reaching the Chilean border at Las Cuevas (3,200 meters).",
      "excursion.altamontania.includes": "Includes:",
      "excursion.altamontania.include1": "Bilingual guide",
      "excursion.altamontania.include2": "Transportation in modern vehicles",
      "excursion.altamontania.notincludes": "Not included:",
      "excursion.altamontania.noinclude1": "Lunch",
      "excursion.altamontania.schedule_title": "Days and times:",
      "excursion.altamontania.schedule": "Monday to Sunday, from 7:30 a.m. to 8:00 p.m.",
      "excursion.altamontania.recommendations_title": "Recommendations:",
      "excursion.altamontania.recommendations": "Warm clothing, comfortable shoes, sunscreen, and sunglasses.",
      "excursion.altamontania.whatsapp": "Hire experience via WhatsApp!",
      "excursion.tourbodegas.title": "Winery Tour",
      "excursion.tourbodegas.subtitle": "Half-day tour visiting two wineries and an olive oil factory.",
      "excursion.tourbodegas.vermas": "see more",
      "excursion.tourbodegas.description": "Half-day wine tour. You'll visit two wineries with tastings included, seeking to contrast them. Afterward, you'll visit an olive oil factory, where you can sample their products.",
      "excursion.tourbodegas.includes": "Includes:",
      "excursion.tourbodegas.include1": "Tickets and tastings",
      "excursion.tourbodegas.include2": "Bilingual guide",
      "excursion.tourbodegas.include3": "Transportation in modern vehicles",
      "excursion.tourbodegas.notincludes": "Not included:",
      "excursion.tourbodegas.noinclude1": "Lunch",
      "excursion.tourbodegas.schedule_title": "Days and times:",
      "excursion.tourbodegas.schedule": "Monday to Saturday, from 2:30 p.m. to 7:00 p.m.",
      "excursion.tourbodegas.recommendations_title": "Recommended:",
      "excursion.tourbodegas.recommendations": "Comfortable shoes, sunscreen, and sunglasses.",
      "excursion.tourbodegas.whatsapp": "Hire experience via WhatsApp",
      "excursion.atuel.title": "Atuel Canyon and San Rafael",
      "excursion.atuel.subtitle": "Full-day tour of Atuel Canyon and San Rafael.",
      "excursion.atuel.vermas": "See more",
      "excursion.atuel.vermenos": "See less",
      "excursion.atuel.description": "Discover southern Mendoza. There, you'll be amazed by the natural beauty of the Atuel Canyon, with its explosion of colors and exotic rock formations alongside artificial lakes. After a tour of San Rafael, we'll return to Mendoza.",
      "excursion.atuel.includes": "Includes:",
      "excursion.atuel.include1": "Bilingual guide",
      "excursion.atuel.include2": "Transportation in modern vehicles",
      "excursion.atuel.notincludes": "Not included:",
      "excursion.atuel.noinclude1": "Lunch",
      "excursion.atuel.noinclude2": "Rafting and catamaran activities",
      "excursion.atuel.schedule_title": "Days and times:",
      "excursion.atuel.schedule": "Thursdays and Sundays, from 7:00 a.m. to 9:00 p.m.",
      "excursion.atuel.recommendations_title": "Recommended:",
      "excursion.atuel.recommendations": "Swimsuit, change of clothes, waterproof shoes, sunscreen, and sunglasses.",
      "excursion.atuel.whatsapp": "Hire experience via WhatsApp",
      "excursion.citytour.title": "City Tour",
      "excursion.citytour.subtitle": "Tour of Mendoza's historic center and main attractions.",
      "excursion.citytour.vermas": "see more",
      "excursion.citytour.description": "Explore Mendoza, visiting its historic center, main squares, Foundation Area, \"La Alameda\" Promenade, Government House, General San Martín Park, and the Cerro de la Gloria viewpoint.",
      "excursion.citytour.includes": "Includes:",
      "excursion.citytour.include1": "Bilingual guide",
      "excursion.citytour.include2": "Transportation in modern vehicles",
      "excursion.citytour.notincludes": "Does not include:",
      "excursion.citytour.noinclude1": "Lunch",
      "excursion.citytour.schedule_title": "Days and times:",
      "excursion.citytour.schedule": "Tuesdays, Thursdays, and Saturdays, from 8:30 a.m. to 12:30 p.m.",
      "excursion.citytour.recommendations_title": "Recommended:",
      "excursion.citytour.recommendations": "Comfortable shoes, sunscreen, and sunglasses.",
      "excursion.citytour.whatsapp": "Hire experience via WhatsApp",
      "excursion.villavicencio.title": "Villavicencio Reserve",
      "excursion.villavicencio.subtitle": "Half-day excursion to explore and photograph the Andean foothills and the Villavicencio Nature Reserve, guided by local reserve guides.",
      "excursion.villavicencio.vermas": "see more",
      "excursion.villavicencio.description": "Half-day tour of the Villavicencio Nature Reserve, where you can take photos of the gorge from above and explore the historic center of the Villavicencio Hotel and its gardens with expert guides.",
      "excursion.villavicencio.includes": "Includes:",
      "excursion.villavicencio.include1": "Bilingual guide",
      "excursion.villavicencio.include2": "Transportation in modern vehicles",
      "excursion.villavicencio.notincludes": "Not included:",
      "excursion.villavicencio.noinclude1": "Admission to and visit to the gardens and surrounding areas of the hotel",
      "excursion.villavicencio.schedule_title": "Days and times:",
      "excursion.villavicencio.schedule": "Wednesdays and Saturdays, from 8:00 a.m. to 1:30 p.m.",
      "excursion.villavicencio.recommendations_title": "Recommended:",
      "excursion.villavicencio.recommendations": "Warm clothing, comfortable shoes, sunscreen, and sunglasses.",
      "excursion.villavicencio.whatsapp": "Hire experience via WhatsApp",
      "excursion.valleuco.title": "Uco Valley and Cordón del Plata",
      "excursion.valleuco.subtitle": "Tour of the Uco Valley with panoramic stops and a visit to wineries.",
      "excursion.valleuco.vermas": "see more",
      "excursion.valleuco.description": "Enjoy a day in the Uco Valley: visit the Cristo Rey panoramic point, the Manzano Histórico, the productive corridor, and take a tour of a local winery (tasting not included). We'll stop at a local restaurant for lunch (not included).",
      "excursion.valleuco.includes": "Includes:",
      "excursion.valleuco.include1": "Bilingual guide",
      "excursion.valleuco.include2": "Transportation in modern vehicles",
      "excursion.valleuco.notincludes": "Not included:",
      "excursion.valleuco.noinclude1": "Lunch",
      "excursion.valleuco.noinclude2": "Admission to the Winery",
      "excursion.valleuco.schedule_title": "Days and times:",
      "excursion.valleuco.schedule": "Fridays, from 8:00 a.m. to 6:00 p.m.",
      "excursion.valleuco.recommendations_title": "Recommended:",
      "excursion.valleuco.recommendations": "Warm clothing, comfortable shoes, sunscreen, and sunglasses.",
      "excursion.valleuco.whatsapp": "Hire experience via WhatsApp",
      "tour.degustando.title": "Tasting Mendoza",
      "tour.degustando.subtitle": "Taste award-winning gin, premium olive oil, and paired wines on a unique tour of Mendoza.",
      "tour.degustando.vermas": "see more",
      "tour.degustando.description": "Explore the flavors of Mendoza by tasting Hilbing Franke's award-winning gin, trying Laur's extra virgin olive oil, and enjoying a menu paired with excellent wines at a prestigious winery.",
      "tour.degustando.includes": "Includes:",
      "tour.degustando.include1": "Guided tours and tastings at the distillery and olive oil mill (or similar)",
      "tour.degustando.include2": "Lunch with a paired menu at Trivento, Monte Quieto, or similar winery",
      "tour.degustando.include3": "High-end vehicle with professional driver",
      "tour.degustando.include4": "Departures Monday through Saturday",
      "tour.degustando.whatsapp": "Hire experience via WhatsApp",  
      "tour.vinosaltura.title": "High Altitude Wines",
      "tour.vinosaltura.subtitle": "Taste high altitude wines, visit exclusive wineries, and enjoy a paired lunch on a unique trip through the Uco Valley.",
      "tour.vinosaltura.vermas": "see more",
      "tour.vinosaltura.description": "Explore the Uco Valley on a unique tour: tasting premium wines grown at over 1,000 meters above sea level, visiting exclusive wineries, and enjoying a paired lunch in a magical setting.",
      "tour.vinosaltura.includes": "Includes:",
      "tour.vinosaltura.include1": "Guided tours and tastings at two wineries (e.g. Andeluna, Familia Blanco, etc.)",
      "tour.vinosaltura.include2": "Paired menu at a third winery (e.g. Andeluna or La Azul)",
      "tour.vinosaltura.include3": "High-end vehicle with professional driver",
      "tour.vinosaltura.include4": "Departures Monday through Sunday",
      "tour.vinosaltura.whatsapp": "Hire experience via WhatsApp",
      "tour.velaswines.title": "Velas & Wines",
      "tour.velaswines.subtitle": "Have lunch at Ojo de Agua winery with a beautiful view of the Andes and sail in Potrerillos tasting garage wines.",
      "tour.velaswines.vermas": "see more",
      "tour.velaswines.description": "Discover Luján de Cuyo with a paired lunch at Ojo de Agua winery, then sail in Potrerillos while tasting garage wines.",
      "tour.velaswines.includes": "Includes:",
      "tour.velaswines.include1": "Sailing trip with tasting (optional: snack board)",
      "tour.velaswines.include2": "Technical briefing",
      "tour.velaswines.include3": "High-end vehicle with professional driver",
      "tour.velaswines.include4": "Departures Monday through Friday",
      "tour.velaswines.whatsapp": "Hire experience via WhatsApp",
      "tour.doc.title": "Malbec D.O.C. Paths",
      "tour.doc.subtitle": "Discover Malbec D.O.C. at wineries in Luján and enjoy a paired menu.",
      "tour.doc.vermas": "see more",
      "tour.doc.description": "Explore Luján de Cuyo following the trail of Malbec D.O.C. and enjoy a unique wine and food experience.",
      "tour.doc.includes": "Includes:",
      "tour.doc.include1": "Guided tours and tastings at two wineries",
      "tour.doc.include2": "Paired menu at a third winery",
      "tour.doc.include3": "High-end vehicle with professional driver",
      "tour.doc.include4": "Departures Monday through Saturday",
      "tour.doc.whatsapp": "Hire experience via WhatsApp",
      
      
    },
    pt: {
      "inicio.title": "INÍCIO",
      "experiencias.title": "EXPERIÊNCIAS",
      "about.title": "SOBRE NÓS",
      "contacto.title": "CONTATO",
      "legal.title": "LEGAL",
      "home.title": "Viva uma experiência única em Mendoza",
      "home.subtitle": "ESCOLHA SUA EXPERIÊNCIA",
      "card.excursiones.title": "Passeios Em Grupo",
      "card.excursiones.description": "Visite Mendoza, aos pés da Cordilheira dos Andes, famosa por sua beleza paisagística, seus vinhos e gastronomia. Passeie por sua bela cidade e arredores de imponentes montanhas, zonas agrícolas e vitivinícolas. Desfrute de suas paisagens espetaculares fazendo atividades na natureza.",
      "card.excursiones.button": "Descobrir",
      "card.winetours.title": "Wine Tours",
      "card.winetours.description": "Viva experiências únicas em enoturismo. De vinícolas boutique a vinhedos históricos, com degustações guiadas, harmonizações e passeios entre vinhedos. Descubra o vinho com especialistas que farão você viver momentos inesquecíveis em ambientes privilegiados.",
      "card.winetours.button": "Descobrir",
      "about.title2":"Quem somos nós?",
      "about.text":"Somos uma pequena empresa dedicada ao serviço turístico em Mendoza, especialmente no setor de enoturismo, dando especial atenção aos nossos passageiros. Dedicados ao turismo receptivo há mais de 25 anos, percorremos um longo caminho até hoje, sendo capazes de compreender e satisfazer as necessidades das pessoas que nos escolhem, desenhando uma experiência única e à medida de acordo com os seus interesses. Sugerimos que você venha fazer conosco uma maravilhosa viagem por Mendoza, com suas montanhas, sua gastronomia, suas vinícolas, seus vinhos e sua gente. Bem-vindo!",
      "contact.title": "Entre em contato por e-mail",
      "contact.subtitle": "Ajudamos você a organizar seus melhores momentos.",
      "form.name.label": "Nome e Sobrenome",
      "form.email.label": "E-mail",
      "form.phone.label": "Telefone",
      "form.message.label": "Mensagem",
      "form.send": "Enviar",
      "contact.whatsapp.title": "Ou envie-nos para o WhatsApp",
      "legal.title2": "Documentos legais",
      "legal.subtitle": "Aqui você pode consultar nossos documentos legais e meios de reclamação. Clique em cada link para baixar o arquivo correspondente.",
      "legal.link1": "CERTIFICADO DE ENDEREÇO VIRTUAL",
      "legal.link2": "HABILITAÇÃO DE LICENÇA",
      "legal.link3": "DEFESA DO CONSUMIDOR",
      "legal.link4": "RECLAMAÇÃO CONTRA UMA AGÊNCIA",
      "filters.title": "Filtrar por:",
      "filters.all": "Mostrar tudo",
      "filters.excursiones": "Passeios Em Grupo",
      "filters.winetours": "Wine Tours",
      "title.excursiones": "Passeios Em Grupo",
      "title.tourwinetours": "Wine Tours",
      "vermas": "Veja mais",
      "vermenos": "Veja menos",
      "excursion.altamontania.title": "Alta Montanha e Puente del Inca",
      "excursion.altamontania.subtitle": "Excursão de dia inteiro pela Cordilheira dos Andes.",
      "excursion.altamontania.vermas": "Veja mais",
      "excursion.altamontania.description": "Excursão de dia inteiro à Cordilheira dos Andes. Passaremos pelos vales de Potrerillos e Uspallata, pelo centro de esqui Los Penitentes, pela Puente del Inca e pelo mirante do Cerro Aconcagua, até chegar à fronteira com o Chile, em Las Cuevas (3.200 metros).",
      "excursion.altamontania.includes": "Inclui:",
      "excursion.altamontania.include1": "Guia bilíngue",
      "excursion.altamontania.include2": "Transporte em unidades modernas",
      "excursion.altamontania.notincludes": "Não inclui:",
      "excursion.altamontania.noinclude1": "Almoço",
      "excursion.altamontania.schedule_title": "Dias e horários:",
      "excursion.altamontania.schedule": "De segunda a domingo, das 07h30 às 20h00.",
      "excursion.altamontania.recommendations_title": "Recomendações:",
      "excursion.altamontania.recommendations": "Roupas de frio, calçados confortáveis, protetor solar e óculos de sol.",
      "excursion.altamontania.whatsapp": "Contratar experiência pelo WhatsApp!",
      "excursion.tourbodegas.title": "Tour de vinícolas",
      "excursion.tourbodegas.subtitle": "Passeio de meio dia visitando duas vinícolas e uma fábrica de azeite.",
      "excursion.tourbodegas.vermas": "veja mais",
      "excursion.tourbodegas.description": "Tour de vinho de meio dia. Serão visitadas duas vinícolas com degustações incluídas, procurando encontrar um contraste entre elas. Mais tarde, visitará uma fábrica de azeite, onde poderá degustar os seus produtos.",
      "excursion.tourbodegas.includes": "Inclui:",
      "excursion.tourbodegas.include1": "Ingressos e degustações",
      "excursion.tourbodegas.include2": "Guia bilíngue",
      "excursion.tourbodegas.include3": "Transporte em unidades modernas",
      "excursion.tourbodegas.notincludes": "Não inclui:",
      "excursion.tourbodegas.noinclude1": "Almoço",
      "excursion.tourbodegas.schedule_title": "Dias e horários:",
     "excursion.tourbodegas.schedule": "segunda a sábado, a partir das 14h30. às 19h00",
      "excursion.tourbodegas.recommendations_title": "Recomendações:",
      "excursion.tourbodegas.recommendations": "calçados confortáveis, protetor solar e óculos de sol.",
      "excursion.tourbodegas.whatsapp": "Contrate experiência pelo whatsapp",
      "excursion.atuel.title": "Cañón del Atuel e San Rafael",
      "excursion.atuel.subtitle": "Excursão de dia inteiro pelo Cañón del Atuel e San Rafael.",
      "excursion.atuel.vermas": "Veja mais",
      "excursion.atuel.vermenos": "Veja menos",
      "excursion.atuel.description": "Descubra o sul de Mendoza, lá você se surpreenderá com as belezas naturais do Cañón del Atuel, com uma explosão de cores e formações rochosas exóticas próximas a espelhos d'água. Após um passeio pela cidade de San Rafael retornaremos à cidade de Mendoza.",
      "excursion.atuel.includes": "Inclui:",
      "excursion.atuel.include1": "Guia bilíngue",
      "excursion.atuel.include2": "Transporte em unidades modernas",
      "excursion.atuel.notincludes": "Não inclui:",
      "excursion.atuel.noinclude1": "Almoço",
      "excursion.atuel.noinclude2": "Atividades de rafting e catamarã",
      "excursion.atuel.schedule_title": "Dias e horários:",
      "excursion.atuel.schedule": "Quintas e domingos, das 7h às 21h.",
      "excursion.atuel.recommendations_title": "Recomendações:",
      "excursion.atuel.recommendations": "Maiô, muda de roupa, calçado impermeável, protetor solar e óculos de sol.",
      "excursion.atuel.whatsapp": "Contrate experiência pelo WhatsApp",
      "excursion.citytour.title": "City Tour Mendoza",
      "excursion.citytour.subtitle": "Passeio pelo centro histórico e principais atrativos de Mendoza.",
      "excursion.citytour.vermas": "veja mais",
      "excursion.citytour.description": "Explore Mendoza visitando seu centro histórico, praças principais, Área Fundacional, Paseo \"La Alameda\", Casa do Governo, Parque General San Martín e o mirante Cerro de la Gloria.",
      "excursion.citytour.includes": "Inclui:",
      "excursion.citytour.include1": "Guia bilíngue",
      "excursion.citytour.include2": "Transporte em unidades modernas",
      "excursion.citytour.notincludes": "Não inclui:",
      "excursion.citytour.noinclude1": "Almoço",
      "excursion.citytour.schedule_title": "Dias e horários:",
      "excursion.citytour.schedule": "terças, quintas e sábados, das 8h30 às 12h30.",
      "excursion.citytour.recommendations_title": "Recomendações:",
      "excursion.citytour.recommendations": "calçados confortáveis, protetor solar e óculos de sol.",
      "excursion.citytour.whatsapp": "Contrate experiência pelo whatsapp",
      "excursion.villavicencio.title": "Reserva Villavicencio",
      "excursion.villavicencio.subtitle": "Excursão de meio dia para descobrir e fotografar a Precordilheira e o desfiladeiro de Villavicencio, conduzida por guias locais da reserva.",
      "excursion.villavicencio.vermas": "veja mais",
      "excursion.villavicencio.description": "Passeio de meio dia pela Reserva Natural Villavicencio onde você poderá tirar fotos do alto do desfiladeiro e conhecer o Centro Histórico do Hotel Villavicencio e seus jardins, com a ajuda de guias especializados.",
      "excursion.villavicencio.includes": "Inclui:",
      "excursion.villavicencio.include1": "Guia bilíngue",
      "excursion.villavicencio.include2": "Transporte em unidades modernas",
      "excursion.villavicencio.notincludes": "Não inclui:",
      "excursion.villavicencio.noinclude1": "Entrada e visita aos jardins e arredores do hotel",
      "excursion.villavicencio.schedule_title": "Dias e horários:",
      "excursion.villavicencio.schedule": "quartas e sábados, das 8h às 13h30.",
      "excursion.villavicencio.recommendations_title": "Recomendações:",
      "excursion.villavicencio.recommendations": "Agasalhos, calçados confortáveis, protetor solar e óculos de sol.",
      "excursion.villavicencio.whatsapp": "Contrate experiência pelo whatsapp",
      "excursion.valleuco.title": "Vale de Uco e Cordón del Plata",
      "excursion.valleuco.subtitle": "Passeio pelo Vale do Uco com paradas panorâmicas e visitas a vinícolas.",
      "excursion.valleuco.vermas": "veja mais",
      "excursion.valleuco.description": "Desfrute de um dia no Vale de Uco: visitando o mirante Cristo Rey, o Manzano histórico, o corredor produtivo e visitando uma vinícola da região (degustação não incluída). Pararemos em um restaurante local para almoçar (não incluído).",
      "excursion.valleuco.includes": "Inclui:",
      "excursion.valleuco.include1": "Guia bilíngue",
      "excursion.valleuco.include2": "Transporte em unidades modernas",
      "excursion.valleuco.notincludes": "Não inclui:",
      "excursion.valleuco.noinclude1": "Almoço",
      "excursion.valleuco.noinclude2": "Entrada para a Vinícola",
      "excursion.valleuco.schedule_title": "Dias e horários:",
      "excursion.valleuco.schedule": "sexta-feira, das 8h às 18h.",
      "excursion.valleuco.recommendations_title": "Recomendações:",
      "excursion.valleuco.recommendations": "Agasalhos, calçados confortáveis, protetor solar e óculos de sol.",
      "excursion.valleuco.whatsapp": "Contrate experiência pelo whatsapp",
      "tour.degustando.title": "Degustando Mendoza",
      "tour.degustando.subtitle": "Prove gin premiado, azeite de oliva de elite e vinhos harmonizados em um passeio exclusivo por Mendoza.",
      "tour.degustando.vermas": "veja mais",
      "tour.degustando.description": "Explore os sabores de Mendoza: experimente o premiado gin Hilbing Franke, prove o azeite virgem extra em Laur e desfrute de um menu acompanhado de vinhos em uma vinícola de prestígio.",
      "tour.degustando.includes": "Inclui:",
      "tour.degustando.include1": "Visitas guiadas e degustações em destilaria e fábrica de azeites (ou similar)",
      "tour.degustando.include2": "Almoço com menu de passos harmonizado com vinhos na vinícola Trivento, Monte Quieto ou similar",
      "tour.degustando.include3": "Veículo de alto padrão com motorista profissional",
      "tour.degustando.include4": "Saídas de segunda a sábado",
      "tour.degustando.whatsapp": "Contrate experiência pelo whatsapp",
      "tour.vinosaltura.title": "Vinhos de Altitude",
      "tour.vinosaltura.subtitle": "Deguste vinhos de altitude, visite vinícolas exclusivas e desfrute de um almoço harmonizado em uma viagem única pelo Vale de Uco.",
      "tour.vinosaltura.vermas": "veja mais",
      "tour.vinosaltura.description": "Explore o Valle de Uco em um passeio único: experimente vinhos de alta qualidade cultivados a mais de 1.000 metros acima do nível do mar, visite vinícolas exclusivas e desfrute de um almoço harmonizado em um ambiente mágico.",
      "tour.vinosaltura.includes": "Inclui:",
      "tour.vinosaltura.include1": "Visitas guiadas e degustação em duas vinícolas (por exemplo, Andeluna, Familia Blanco, etc.)",
      "tour.vinosaltura.include2": "Menu de passos harmonizado com vinhos em uma terceira vinícola (por exemplo, Andeluna ou La Azul)",
      "tour.vinosaltura.include3": "Veículo de alto padrão com motorista profissional",
      "tour.vinosaltura.include4": "Saídas de segunda a domingo",
      "tour.vinosaltura.whatsapp": "Contrate experiência pelo whatsapp",
      "tour.velaswines.title": "Velas e Vinhos",
      "tour.velaswines.subtitle": "Almoço em Ojo de Agua com vista para a Cordilheira dos Andes e navegação em Potrerillos degustando vinhos de garagem.",
      "tour.velaswines.vermas": "veja mais",
      "tour.velaswines.description": "Descubra Luján de Cuyo com um almoço harmonizado na vinícola Ojo de Agua e depois navegue em Potrerillos enquanto degusta vinhos de garagem.",
      "tour.velaswines.includes": "Inclui:",
      "tour.velaswines.include1": "Passeio de barco à vela com degustação (opcional: tábua de frios e queijos)",
      "tour.velaswines.include2": "Palestra técnica",
      "tour.velaswines.include3": "Veículo de alto padrão com motorista profissional",
      "tour.velaswines.include4": "Saídas de segunda a sexta",
      "tour.velaswines.whatsapp": "Contrate experiência pelo whatsapp",
      "tour.doc.title": "Caminhos do Malbec D.O.C.",
      "tour.doc.subtitle": "Descubra Malbec D.O.C. nas vinícolas de Luján e desfrute de um menu harmonizado.",
      "tour.doc.vermas": "veja mais",
      "tour.doc.description": "Explore Luján de Cuyo seguindo os passos do Malbec D.O.C. e desfrute de uma experiência com vinhos e gastronômica única.",
      "tour.doc.includes": "Inclui:",
      "tour.doc.include1": "Visitas guiadas e degustação em duas vinícolas",
      "tour.doc.include2": "Menu de passos harmonizado em uma terceira vinícola",
      "tour.doc.include3": "Veículo de alto padrão com motorista profissional",
      "tour.doc.include4": "Saídas de segunda a sábado",
      "tour.doc.whatsapp": "Contrate experiência pelo whatsapp",
     
    }
  };
  
  function setLanguage(lang) {
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      const translation = translations[lang][key];
      if (translation) {
        el.innerText = translation;
      }
    });
  }
  
  document.addEventListener('DOMContentLoaded', () => {
    setLanguage('es'); // 🔥 SIEMPRE arranca en Español
  });
  
